version: "3.9"

services:
  backend:
    container_name: "deployment-service"
    build: .
    working_dir: /app
    command: uvicorn app.__main__:app --host 0.0.0.0 --port 8088 --reload
    ports:
      - "8088:8088"
    volumes:
      - .:/app
    restart: always