version: "3.9"

services:
  backend:
    container_name: "deployment-service"
    build: .
    working_dir: /app
    command: uvicorn app.__main__:app --host 0.0.0.0 --port 8088 --reload
    ports:
      - "8088:8088"
    environment:
      - DOCKER_CLIENT_URL=unix://var/run/docker.sock
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
